# Generated by Django 4.2.30 on 2026-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
