# Generated by Django 4.2.30 on 2026-09-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_assigned_users_project_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_tasks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
