# Generated by Django 4.2.30 on 2026-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
