# Generated by Django 4.2.30 on 2026-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='task_created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
